<<<<<<< HEAD
services:
  - type: web
    name: cocoapi
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
=======
services:
  - type: web
    name: cocoapi
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
>>>>>>> b755c11 (Primer push completo del proyecto cocoapi)
